# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5fb13ae3c324e5c684360be979a2ab30ee00f4571bd15b08ac75a88350bab1889450e49d8425fd5fdf8cd5bed19d1ead98b2135d3b50c8ceda25e216a7bf660

test:
  secret_key_base: 48a3f72289380774d63ec625d080f9a2bce7337d39f9b7b5837652e0d6cd82c6d75bf2d85ded608163295e2e25236b4b6555e2ec1eed68516645e93075710872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
